# -*- coding: utf-8 -*-
"""credit_card_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qot_HwxP1OW5ziM1C_TdD5p3HY9IUkda

## Credit Card Fraud Detection

  ### Introduction
        This project aims to build a machine learning model to detect fradulent credit card transaction.
        The dataset used for this project is sourced from kaggle and contains information about credit card transaction made by European cardholders in september 2023.
        The dataset is highly imbalanced, with a small fraction of transaction labeled as fraudulent.

### Download and load dataset.
"""

!pip install opendatasets
import opendatasets as od

url = "https://www.kaggle.com/datasets/nelgiriyewithana/credit-card-fraud-detection-dataset-2023"
dataset = od.download(url)

"""### Exploratory Data Analysis

  - Shape of the dataset
  - Dataset info
  - Missing values handling
  - Stats
    
"""

import pandas as pd

df = pd.read_csv('/content/credit-card-fraud-detection-dataset-2023/creditcard_2023.csv')

print(df.head(10))

df.shape

df.info()

df.isna().sum()

df.describe()

# class distribution
distribution = df.Class.value_counts()
print(distribution)

#plotting
import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x=df['Class'],data=df)
plt.xlabel('Class')
plt.ylabel('Count')
plt.show

"""### Dataset Spliting into input/output"""

x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

"""### Data Segregation into train and test data"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""### Data standardization"""

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train) # Fit and transform x_train
x_test = sc.transform(x_test) # Transform x_test using the fitted scaler

"""### Finding best model"""

# for best k_value
error = []

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


for i in range(1,45):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  pred = model.predict(x_test)
  error.append(np.mean(pred != y_test))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(range(1,45),error,color='green',m='o',ms=5,mfc='red')
plt.xlabel('Kmeans')
plt.ylabel('Error')

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models = {'LR':LogisticRegression(),
          'CART':DecisionTreeClassifier(),
          'KNN':KNeighborsClassifier(n_neighbors=7),
          'SVM':SVC(),
          'RFR':RandomForestClassifier()}

score = {}
for name, model in models.items():
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  score[name] = accuracy_score(y_test,y_pred)

plt.figure(figsize=(10,5))
plt.bar(score.keys(),score.values(),color='green')
plt.xlabel('Models')
plt.ylabel('Accuracy')